# Generated by Django 4.2.6 on 2023-10-27 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231026_0141'),
        ('pengunjung', '0001_initial'),
        ('deskripsi_buku', '0002_auto_20231026_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentar', models.TextField()),
                ('rating_user', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengunjung.pengunjung')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
